services:
  pg1:
    image: postgres:17.1
    restart: always
    shm_size: 128mb
    ports:
      - 5441:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./pgdata1:/var/lib/postgresql/data
  pg2:
    image: postgres:17.1
    restart: always
    shm_size: 128mb
    ports:
      - 5442:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./pgdata2:/var/lib/postgresql/data
  pg3:
    image: postgres:17.1
    restart: always
    shm_size: 128mb
    ports:
      - 5443:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./pgdata3:/var/lib/postgresql/data